/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5       */
/*  Created On : 30-abr-2026 18:16:07                   */
/*  DBMS       : SQL Server 2012                        */
/* ---------------------------------------------------- */

/* 1. Eliminar Restricciones de Clave Foránea (Drop Foreign Keys) */

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'fktiene_Cliente')
    ALTER TABLE [Cuenta] DROP CONSTRAINT [fktiene_Cliente];
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'fktiene_Transaccion')
    ALTER TABLE [DetalleTransaccio] DROP CONSTRAINT [fktiene_Transaccion];
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'fkse realiza en_Transaccion')
    ALTER TABLE [Terminal] DROP CONSTRAINT [fkse realiza en_Transaccion];
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'fk_se realiza en_Transaccion')
    ALTER TABLE [Transaccion] DROP CONSTRAINT [fk_se realiza en_Transaccion];
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'fk_realiza_Cuenta')
    ALTER TABLE [Transaccion] DROP CONSTRAINT [fk_realiza_Cuenta];
GO

/* 2. Eliminar Tablas (Drop Tables) */

IF OBJECT_ID('[Terminal]', 'U') IS NOT NULL DROP TABLE [Terminal];
IF OBJECT_ID('[DetalleTransaccio]', 'U') IS NOT NULL DROP TABLE [DetalleTransaccio];
IF OBJECT_ID('[Transaccion]', 'U') IS NOT NULL DROP TABLE [Transaccion];
IF OBJECT_ID('[Cuenta]', 'U') IS NOT NULL DROP TABLE [Cuenta];
IF OBJECT_ID('[Comercio]', 'U') IS NOT NULL DROP TABLE [Comercio];
IF OBJECT_ID('[Cliente]', 'U') IS NOT NULL DROP TABLE [Cliente];
GO

/* 3. Crear Tablas (Create Tables) */

CREATE TABLE [Cliente] (
    [idCliente] int NOT NULL,
    [nombre] nvarchar(100) NOT NULL,
    CONSTRAINT [pkCliente] PRIMARY KEY CLUSTERED ([idCliente] ASC)
);
GO

CREATE TABLE [Comercio] (
    [idComercio] int NOT NULL,
    [nombreComercio] nvarchar(50) NOT NULL,
    [direccion] nvarchar(200) NULL,
    CONSTRAINT [pkComercio] PRIMARY KEY CLUSTERED ([idComercio] ASC)
);
GO

CREATE TABLE [Cuenta] (
    [numCuenta] nvarchar(20) NOT NULL,
    [idCliente] int NOT NULL,
    CONSTRAINT [pkCuenta] PRIMARY KEY CLUSTERED ([numCuenta] ASC)
);
GO

CREATE TABLE [Transaccion] (
    [idTransaccion] int NOT NULL,
    [referencia] nvarchar(50) NOT NULL,
    [autorizacion] nvarchar(50) NOT NULL,
    [fecha] date NOT NULL,
    [hora] time(7) NOT NULL,
    [monto] decimal(18,2) NOT NULL, -- Agregada precisión decimal
    [tipoCambio] decimal(10,4) NULL,   -- Agregada precisión decimal
    [tipoTransaccion] nvarchar(30) NOT NULL,
    [idComercio] int NOT NULL,
    [numCuenta] nvarchar(20) NOT NULL,
    CONSTRAINT [pkTransaccion] PRIMARY KEY CLUSTERED ([idTransaccion] ASC)
);
GO

CREATE TABLE [DetalleTransaccio] (
    [idDetalle] int NOT NULL,
    [detalle] nvarchar(255) NULL,
    [montoPagado] decimal(18,2) NOT NULL,
    [idTransaccion] int NOT NULL,
    CONSTRAINT [pkDetalleTransaccio] PRIMARY KEY CLUSTERED ([idDetalle] ASC)
);
GO

CREATE TABLE [Terminal] (
    [idTerminal] int NOT NULL,
    [lote] nchar(10) NOT NULL,
    [idTransaccion] int NOT NULL,
    CONSTRAINT [pkTerminal] PRIMARY KEY CLUSTERED ([idTerminal] ASC)
);
GO

/* 4. Crear Restricciones de Clave Foránea (Foreign Keys) */

ALTER TABLE [Cuenta] ADD CONSTRAINT [fktiene_Cliente]
    FOREIGN KEY ([idCliente]) REFERENCES [Cliente] ([idCliente]);
GO

ALTER TABLE [DetalleTransaccio] ADD CONSTRAINT [fktiene_Transaccion]
    FOREIGN KEY ([idTransaccion]) REFERENCES [Transaccion] ([idTransaccion]);
GO

-- CORRECCIÓN: Se añadió la referencia a la tabla Transaccion que estaba vacía
ALTER TABLE [Terminal] ADD CONSTRAINT [fkse realiza en_Transaccion]
    FOREIGN KEY ([idTransaccion]) REFERENCES [Transaccion] ([idTransaccion]);
GO

ALTER TABLE [Transaccion] ADD CONSTRAINT [fk_se realiza en_Transaccion]
    FOREIGN KEY ([idComercio]) REFERENCES [Comercio] ([idComercio]);
GO

ALTER TABLE [Transaccion] ADD CONSTRAINT [fk_realiza_Cuenta]
    FOREIGN KEY ([numCuenta]) REFERENCES [Cuenta] ([numCuenta]);
GO

/* 5. Comentarios de Tabla (Extended Properties) */

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Persona dueña de la cuenta bancaria.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Cliente';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Lugar donde se realizó la transacción.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Comercio';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Cuenta bancaria asociada al cliente.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Cuenta';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Operación realizada.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Transaccion';
GO
